<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CBsXvLI' shared service.

return $this->privates['.service_locator.CBsXvLI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EmployerServiceController::accueil' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
    'App\\Controller\\EmployerServiceController::delete' => ['privates', '.service_locator.eUhKckg', 'get_ServiceLocator_EUhKckgService.php', true],
    'App\\Controller\\EmployerServiceController:accueil' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
    'App\\Controller\\EmployerServiceController:delete' => ['privates', '.service_locator.eUhKckg', 'get_ServiceLocator_EUhKckgService.php', true],
], [
    'App\\Controller\\EmployerServiceController::accueil' => '?',
    'App\\Controller\\EmployerServiceController::delete' => '?',
    'App\\Controller\\EmployerServiceController:accueil' => '?',
    'App\\Controller\\EmployerServiceController:delete' => '?',
]);
