<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..TeQc9r' shared service.

return $this->privates['.service_locator..TeQc9r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'service' => ['privates', '.errored..service_locator..TeQc9r.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator..TeQc9r": it references class "App\\Entity\\Service" but no such service exists.'],
], [
    'manager' => '?',
    'service' => 'App\\Entity\\Service',
]);
