<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLel6P2J\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLel6P2J/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLel6P2J.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLel6P2J\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLel6P2J\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Lel6P2J',
    'container.build_id' => '2ce28afc',
    'container.build_time' => 1563147468,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLel6P2J');
